### ISSUE TITLE
kernel BUG at drivers/gpu/arm/bifrost_for_linux/mali_kbase_mem_linux.c:1762!

### ISSUE THREAD

**Issue by giuliobenetti** [bootlin/mali-driver#2]
@trombonebuster, I've moved to an Issue as it should be.

Ah RK3399, now I’ve seen. What sounds strange to me is the path of driver:
drivers/gpu/arm/bifrost_for_linux/mali_kbase_mem_linux.c

That “bifrost_for_linux”.

How have you built the driver?
Have you built it like a module or have you tried copying it directly into kernel while changing its directory name?

Also the error on line 1762 of mali_kbase_mem_linux.c doesn’t have the call to kbase_cpu_vm_close().

So can you describe me how you’ve built the driver?
As an external module or in another way?
Using a build system?(i.e. Buildroot)

I’m going to reproduce the building soon to compare and debug. But I need to be sure to use the same sources.

Thank you!

_Originally posted by @giuliobenetti in https://github.com/bootlin/mali-driver/issues/1#issuecomment-1019332849_

**Comment by giuliobenetti** [comment]
@trombonebuster take care that RK3399 does have a Midgard Mali "ARM Mali-T860MP4". The current driver is Midgard anyway so it should work. But RK3399 is not Bifrost.

**Comment by giuliobenetti** [comment]
@trombonebuster I see you're using Linux 5.15.0-rc7, can you please use latest stable Linux 5.15.16 and let me know?

NOTE: It's never a good idea using a -rcX version. It could be a Linux problem itself instead of the driver.
Thank you

**Comment by trombonebuster** [comment]
@giuliobenetti , thanks for the response! I am building the drivers directly in the kernel. I have been using these drivers with 4.4 and OpenCL with great success, and I would like to adapt them to work with mainline. I originally went through the build errors one by one and made the necessary changes, which were mostly the same changes that I saw in this repo, however I received the same segmentation fault from the kernel as I did with yours.

The directory is named wrong. Whoever was working with the repo on this server before me renamed the directory to bifrost_for_linux even though it says  midgard_for_linux in our kernel repo.

I built your drivers into the kernel by making a copy of my working directory and replacing the necessary files with yours (All except the make and platform files). 

I will try building with 5.15.16 as you suggested. Thanks for your help! Please let me know if you have any other insights. 

Also, the board I'm working with closely resembles the rock960 boards with Mali-T860 on board.

**Comment by giuliobenetti** [comment]
@trombonebuster Oh, so what is not clear to me is if the driver works in general and it only fails on the call of clinfo().
Is it like that? Or it simply doesn't work at all?
I'm going to have a try as soon as I can(time is always few :-/)

**Comment by trombonebuster** [comment]
@giuliobenetti , Oh! I'm sorry. Yes i get /dev/mali0 but it fails when calling clinfo after I've installed the userspace drivers that I was using with 4.4 . Also dmesg looks the same as with 4.4 with one exception. I'm missing the following line that was in 4.4 -     2.853296] mali ff9a0000.gpu: l=0 h=2147483647 hyst=5000 l_limit=0 h_limit=0.

Here is the full dmesg output with 4.4 -
[    2.046061] mali ff9a0000.gpu: Looking up mali-supply from device tree
[    2.046084] mali ff9a0000.gpu: Failed to get regulator
[    2.046559] mali ff9a0000.gpu: Power control initialization failed
[    2.847261] mali ff9a0000.gpu: Looking up mali-supply from device tree
[    2.849732] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[    2.851222] mali ff9a0000.gpu: Protected mode not available
[    2.853296] mali ff9a0000.gpu: l=0 h=2147483647 hyst=5000 l_limit=0 h_limit=0
[    2.854411] mali ff9a0000.gpu: Using configured power model mali-simple-power-model, and fallback mali-simple-power-model
[    2.857026] mali ff9a0000.gpu: Probed as mali0

Here is full output for 5.15 - rc7 -
[    3.227777] vdd_gpu: will resolve supply early: vin
[    3.227844] vdd_gpu: supplied by vcc5v0_sys
[    3.229535] vdd_gpu: 712 <--> 1500 mV at 1000 mV, enabled
[    4.986640] mali ff9a0000.gpu: Looking up mali-supply from device tree
[    4.988086] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[    4.988794] mali ff9a0000.gpu: Protected mode not available
[    4.989891] mali ff9a0000.gpu: Using configured power model mali-simple-power-model, and fallback mali-simple-power-model
[    4.991596] mali ff9a0000.gpu: Probed as mali0

**Comment by giuliobenetti** [comment]
@trombonebuster thanks for pointing. That line shouldn't change that much. Do you use Mali only for OpenCL? Or also for OpenGL?
I ask you because I see that userspace blobs that Rockchip gives are only for OpenGL for t86x, while they give the cl file for G31 only. At least I deduce this from their names:
https://github.com/rockchip-linux/libmali/tree/master/lib
Here I only have 2 boards with RK3288 so it's an ARM32 and not AARCH64, but I'm going to give a try.

**Comment by trombonebuster** [comment]
@giuliobenetti , I've only been using Mali for OpenCL, building with ArmNN and tensorflow for a machine learning project. 
The userspace drivers were built from rockchip/libmali https://github.com/rockchip-linux/libmali . The ones I'm using were prebuilt for rock960. I am no longer able to find the debian packages online, but I am happy to send them to you. They are built for arm64, so they should work.

**Comment by trombonebuster** [comment]
Here is a dropbox link to the userspace drivers - https://www.dropbox.com/sh/90hbbu82h2op7ot/AACWRWqYTusB9rFBJhc-ReBZa?dl=0

**Comment by trombonebuster** [comment]
@giuliobenetti , using latest stable worked! Thanks so much for your help! Let me know if there is anything I can do for you in the future!

**Comment by trombonebuster** [comment]
oops nevermind. I used the wrong kernel image

**Comment by giuliobenetti** [comment]
@trombonebuster so it still doesn't work?

**Comment by trombonebuster** [comment]
I'm burning an image with latest stable kernel now. I inadvertently used the 4.4 image due to not changing the config on my build properly.

**Comment by giuliobenetti** [comment]
@trombonebuster happy to know it :-) You’re welcome!
