### ISSUE TITLE
Linux 6.1 support test

### ISSUE THREAD

**Issue by giuliobenetti** [bootlin/mali-driver#6]
Hi @AustinSchuh!

Do you mind give a try to this branch:
https://github.com/bootlin/mali-driver/tree/fix/linux-6.1
with Linux 6.1?
There is a patch there that fixes the build but I need some runtime testing.

Thanks in advance.

Btw, I've forgotten to add your Reviewed-by on previous patch, sorry.

**Comment by AustinSchuh** [comment]
I'll give it a whirl, but I'm on 6.0.8-rt14 kernel so that'll take more time to get setup.

**Comment by vsnrain** [comment]
Hi @giuliobenetti 

Not sure if it helps, I tested it on VIM3L board 6.1.7-1-MANJARO-ARM-AML kernel with [libmali-bifrost-g31-rxp0-gbm.so](https://github.com/Txwv/rockchip-linux-libmali/tree/master/lib/aarch64-linux-gnu) blobs.

Either it does not seem to work, or I messed something during install. Any hints what may be the issue?

[weston.log.txt](https://github.com/bootlin/mali-driver/files/10745572/weston.log.txt)
[glmark2.log.txt](https://github.com/bootlin/mali-driver/files/10745571/glmark2.log.txt)
[clinfo.log.txt](https://github.com/bootlin/mali-driver/files/10745573/clinfo.log.txt)

**Comment by giuliobenetti** [comment]
Thanks a lot @vsnrain for testing,

from the stackframe I see in glmark2.log.txt the function that fails with NULL pointer is:
dma_resv_add_fence()
but this is not related to Linux 6.1 fix.
Does the driver work with Linux 5.18, 5.19 and 6.0?
Could you please test it?

Also, which board and SoC are you using?

**Comment by cbalint13** [comment]
@giuliobenetti ,

I've tested it on rk3399 NanoPC-T2 with ```6.2.9-300.fc38.aarch64```
It loads, but probing it with ocl fails with kernel crash, see outputs below.
Previous old 4.4.x official kernel from FriendlyElec worked fine with OpenCL.

Let me know if this 6.x tree can be fixed, I am interested to follow.

---

* Used patch:
```diff --git a/r8p0/drivers/gpu/arm/midgard/mali_kbase_mem_linux.c b/r8p0/drivers/gpu/arm/midgard/mali_kbase_mem_linux.c
index 710ebac..7cdf1a9 100644
--- a/r8p0/drivers/gpu/arm/midgard/mali_kbase_mem_linux.c
+++ b/r8p0/drivers/gpu/arm/midgard/mali_kbase_mem_linux.c
@@ -2514,7 +2514,7 @@ KBASE_EXPORT_TEST_API(kbase_vunmap);
 #if (LINUX_VERSION_CODE >= KERNEL_VERSION(5, 5, 0))
 static void mali_add_mm_counter(struct mm_struct *mm, int member, long value)
 {
-       atomic_long_add(value, &mm->rss_stat.count[MM_FILEPAGES]);
+       percpu_counter_add(&mm->rss_stat[MM_FILEPAGES], value);
 }
 #else
 static void mali_add_mm_counter(struct mm_struct *mm, int member, long value)
```

* Kernel loading:

```

# dmesg | grep mali
[   21.078657] mali_kbase: loading out-of-tree module taints kernel.
[   21.082991] mali_kbase: module verification failed: signature and/or required key missing - tainting kernel
[   21.167863] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[   21.168701] mali ff9a0000.gpu: Protected mode not available
[   21.178130] mali ff9a0000.gpu: Probed as mali0
```

* OpenCL device probing using [clDeviceQuery.cpp](https://gist.github.com/tserj/ed03e874d288be2a485089feed5ac08f#file-cldevicequery-cpp) :
```[  412.755821] ------------[ cut here ]------------
[  412.756241] WARNING: CPU: 4 PID: 1038 at mm/memory.c:5175 handle_mm_fault+0x274/0x290
[  412.756938] Modules linked in: bnep vfat fat brcmfmac_wcc btsdio snd_soc_simple_card snd_soc_hdmi_codec brcmfmac snd_soc_simple_card_utils snd_soc_rockchip_i2s snd_soc_core hantro_vpu rockchip_vdec(C) snd_compress ac97_bus snd_pcm_dmaengine snd_seq snd_seq_device gpio_ir_recv snd_pcm leds_gpio mali_kbase(OE) snd_timer brcmutil hci_uart v4l2_vp9 snd soundcore cfg80211 btqca btrtl v4l2_h264 btbcm rockchip_rga videobuf2_dma_contig btintel videobuf2_dma_sg videobuf2_memops v4l2_mem2mem videobuf2_v4l2 bluetooth videobuf2_common videodev dwmac_rk stmmac_platform rfkill mc stmmac pcs_xpcs phylink rockchip_saradc industrialio_triggered_buffer rockchip_thermal kfifo_buf coresight_cpu_debug coresight cpufreq_dt lz4 lz4_compress zram fuse loop xhci_plat_hcd mmc_block dwc3 dw_hdmi_cec dw_hdmi_i2s_audio ulpi udc_core panfrost rockchipdrm nvme fusb302 crct10dif_ce polyval_ce polyval_generic ghash_ce dwc3_of_simple pwm_fan gpio_keys drm_dma_helper gpu_sched des_generic phy_rockchip_emmc analogix_dp
[  412.757109]  rk_crypto tcpm nvme_core dw_mipi_dsi libdes dw_hdmi phy_rockchip_inno_usb2 rtc_rk808 sdhci_of_arasan dw_wdt adc_keys ohci_platform drm_display_helper sdhci_pltfm typec pl330 industrialio ohci_hcd io_domain phy_rockchip_typec nvme_common sdhci nvmem_rockchip_efuse dw_mmc_rockchip pwm_rockchip cec dw_mmc_pltfm ehci_platform dw_mmc cqhci scsi_dh_rdac scsi_dh_emc scsi_dh_alua dm_multipath
[  412.767776] CPU: 4 PID: 1038 Comm: clDeviceQuery Tainted: G         C OE      6.2.9-300.fc38.aarch64 #1
[  412.768600] Hardware name: Unknown Unknown Product/Unknown Product, BIOS 2023.01 01/01/2023
[  412.769330] pstate: 80400005 (Nzcv daif +PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[  412.769941] pc : handle_mm_fault+0x274/0x290
[  412.770320] lr : handle_mm_fault+0xbc/0x290
[  412.770691] sp : ffff80000d5bbda0
[  412.770983] x29: ffff80000d5bbda0 x28: ffff000007c8a1c0 x27: 0000000000000002
[  412.771614] x26: ffff0000078ac460 x25: 0000000000000255 x24: 0000000000000000
[  412.772243] x23: ffff000006681000 x22: ffff80000d5bbeb0 x21: 0000ffff930f1000
[  412.772873] x20: ffff0000049df2f8 x19: 0000000000000255 x18: 0000000000000000
[  412.773502] x17: 0000000000000000 x16: 0000000000000000 x15: ffff8000095f4f10
[  412.774131] x14: ffff0000078ac400 x13: 1fffe0000084dba1 x12: ffffffffffffffff
[  412.774760] x11: 0000ffff930e8000 x10: 0000ffff930f1000 x9 : ffff8000084d7c4c
[  412.775388] x8 : 0000000000000000 x7 : ffff00000426dd00 x6 : 000000000000000a
[  412.776015] x5 : ffff000007c8a1c0 x4 : 0000000000000000 x3 : 00000000000000c0
[  412.776644] x2 : ffff000007c8a1c0 x1 : 0000000000000000 x0 : 00000000040644cb
[  412.777273] Call trace:
[  412.777491]  handle_mm_fault+0x274/0x290
[  412.777841]  do_page_fault+0x1f4/0x53c
[  412.778176]  do_mem_abort+0x4c/0xa0
[  412.778488]  el0_da+0x48/0x120
[  412.778762]  el0t_64_sync_handler+0xe4/0x120
[  412.779142]  el0t_64_sync+0x194/0x198
[  412.779467] ---[ end trace 0000000000000000 ]---

```

**Comment by giuliobenetti** [comment]
> Hi @giuliobenetti
> 
> Not sure if it helps, I tested it on VIM3L board 6.1.7-1-MANJARO-ARM-AML kernel with [libmali-bifrost-g31-rxp0-gbm.so](https://github.com/Txwv/rockchip-linux-libmali/tree/master/lib/aarch64-linux-gnu) blobs.

Hi @vsnrain,
sorry for the late reply. Thanks for testing. Am I wrong or VIM3L board is Amlogic based?
https://www.khadas.com/vim3l
Let me know if I'm correct or please provide me a pointer to the board's URL.

If it is you can't use Rockchip[0] blobs on Amlogic SoC, you need Amlogic ones.

[0]: https://github.com/Txwv/rockchip-linux-libmali/tree/master/lib/aarch64-linux-gnu

**Comment by cbalint13** [comment]
@giuliobenetti ,
> Yes it can be fixed, the problem is the time to dedicate. I still need to finish to setup a Buildroot BSP for PX30 MiniEVB to test on G31.

First thank you for your effort and dedication !

> thank you for testing and providing Linux 6.2 patch. In the meanwhile would it be possible for you to test mali-driver on with Linux 5.18, 5.19 and 6.0? Because I suspect there is a bug on previous patches. This would help me a lot to identify where the problem is without having a working board on my side.

Seems that ```linux-6.1``` branch (original, no additional 6.2 patches) works fine with a stock ```6.1.18``` fedora kernel:


```
# uname -a
Linux rk3399 6.1.18-200.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:03:54 UTC 2023 aarch64 GNU/Linux

# dmesg | grep mali
[  363.380775] mali_kbase: loading out-of-tree module taints kernel.
[  363.383877] mali_kbase: module verification failed: signature and/or required key missing - tainting kernel
[  363.394549] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
[  363.395185] mali ff9a0000.gpu: Protected mode not available
[  363.396514] mali ff9a0000.gpu: Probed as mali0

# ./clDeviceQuery 
clDeviceQuery Starting...

1 OpenCL Platforms found

 CL_PLATFORM_NAME: 	ARM Platform
 CL_PLATFORM_VERSION: 	OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3
OpenCL Device Info:

 1 devices found supporting OpenCL on: ARM Platform

 ----------------------------------
 Device Mali-T860
 ---------------------------------
  CL_DEVICE_NAME: 			Mali-T860
  CL_DEVICE_VENDOR: 			ARM
  CL_DRIVER_VERSION: 			1.2
  CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
  CL_DEVICE_MAX_COMPUTE_UNITS:		4
  CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
  CL_DEVICE_MAX_WORK_ITEM_SIZES:	256 / 256 / 256 
  CL_DEVICE_MAX_WORK_GROUP_SIZE:	256
  CL_DEVICE_MAX_CLOCK_FREQUENCY:	500 MHz
  CL_DEVICE_ADDRESS_BITS:		64
  CL_DEVICE_MAX_MEM_ALLOC_SIZE:		952 MByte
  CL_DEVICE_GLOBAL_MEM_SIZE:		3809 MByte
  CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
  CL_DEVICE_LOCAL_MEM_TYPE:		global
  CL_DEVICE_LOCAL_MEM_SIZE:		32 KByte
  CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
  CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
  CL_DEVICE_IMAGE_SUPPORT:		1
  CL_DEVICE_MAX_READ_IMAGE_ARGS:	128
  CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	8

  CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 65536
					2D_MAX_HEIGHT	 65536
					3D_MAX_WIDTH	 65536
					3D_MAX_HEIGHT	 65536
					3D_MAX_DEPTH	 65536
  CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 16, SHORT 8, INT 4, FLOAT 2, DOUBLE 4


clDeviceQuery, Platform Name = ARM Platform, Platform Version = OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3, NumDevs = 1, Device = Mali-T860
```
As addition I was able to run a opencl kernel without problems:
```
//OpenCL kernel which is run for every work item created.
const char *saxpy_kernel =
"__kernel                                   \n"
"void saxpy_kernel(float alpha,     \n"
"                  __global float *A,       \n"
"                  __global float *B,       \n"
"                  __global float *C)       \n"
"{                                          \n"
"    //Get the index of the work-item       \n"
"    int index = get_global_id(0);          \n"
"    C[index] = alpha* A[index] + B[index]; \n"
"}  
```

I am interested only in OpenCL capability, please let me know if you need any kind of additional tests.

**Comment by giuliobenetti** [comment]
> > thank you for testing and providing Linux 6.2 patch. In the meanwhile would it be possible for you to test mali-driver on with Linux 5.18, 5.19 and 6.0? Because I suspect there is a bug on previous patches. This would help me a lot to identify where the problem is without having a working board on my side.
> 
> Seems that `linux-6.1` branch (original, no additional 6.2 patches) works fine with a stock `6.1.18` fedora kernel:

Ah, so it works on Linux 6.1, good to know, so I can push the patch for Linux 6.1.
I didn't read correctly that you have problems on Linux 6.2 only for which you've provided the patch.
Let me check your patch and see if it looks correct to me then.

> ```
> # uname -a
> Linux rk3399 6.1.18-200.fc37.aarch64 #1 SMP PREEMPT_DYNAMIC Sat Mar 11 16:03:54 UTC 2023 aarch64 GNU/Linux
> 
> # dmesg | grep mali
> [  363.380775] mali_kbase: loading out-of-tree module taints kernel.
> [  363.383877] mali_kbase: module verification failed: signature and/or required key missing - tainting kernel
> [  363.394549] mali ff9a0000.gpu: GPU identified as 0x0860 r2p0 status 0
> [  363.395185] mali ff9a0000.gpu: Protected mode not available
> [  363.396514] mali ff9a0000.gpu: Probed as mali0
> 
> # ./clDeviceQuery 
> clDeviceQuery Starting...
> 
> 1 OpenCL Platforms found
> 
>  CL_PLATFORM_NAME: 	ARM Platform
>  CL_PLATFORM_VERSION: 	OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3
> OpenCL Device Info:
> 
>  1 devices found supporting OpenCL on: ARM Platform
> 
>  ----------------------------------
>  Device Mali-T860
>  ---------------------------------
>   CL_DEVICE_NAME: 			Mali-T860
>   CL_DEVICE_VENDOR: 			ARM
>   CL_DRIVER_VERSION: 			1.2
>   CL_DEVICE_TYPE:			CL_DEVICE_TYPE_GPU
>   CL_DEVICE_MAX_COMPUTE_UNITS:		4
>   CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS:	3
>   CL_DEVICE_MAX_WORK_ITEM_SIZES:	256 / 256 / 256 
>   CL_DEVICE_MAX_WORK_GROUP_SIZE:	256
>   CL_DEVICE_MAX_CLOCK_FREQUENCY:	500 MHz
>   CL_DEVICE_ADDRESS_BITS:		64
>   CL_DEVICE_MAX_MEM_ALLOC_SIZE:		952 MByte
>   CL_DEVICE_GLOBAL_MEM_SIZE:		3809 MByte
>   CL_DEVICE_ERROR_CORRECTION_SUPPORT:	no
>   CL_DEVICE_LOCAL_MEM_TYPE:		global
>   CL_DEVICE_LOCAL_MEM_SIZE:		32 KByte
>   CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE:	64 KByte
>   CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE
>   CL_DEVICE_QUEUE_PROPERTIES:		CL_QUEUE_PROFILING_ENABLE
>   CL_DEVICE_IMAGE_SUPPORT:		1
>   CL_DEVICE_MAX_READ_IMAGE_ARGS:	128
>   CL_DEVICE_MAX_WRITE_IMAGE_ARGS:	8
> 
>   CL_DEVICE_IMAGE <dim>			2D_MAX_WIDTH	 65536
> 					2D_MAX_HEIGHT	 65536
> 					3D_MAX_WIDTH	 65536
> 					3D_MAX_HEIGHT	 65536
> 					3D_MAX_DEPTH	 65536
>   CL_DEVICE_PREFERRED_VECTOR_WIDTH_<t>	CHAR 16, SHORT 8, INT 4, FLOAT 2, DOUBLE 4
> 
> 
> clDeviceQuery, Platform Name = ARM Platform, Platform Version = OpenCL 1.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3, NumDevs = 1, Device = Mali-T860
> ```
> 
> As addition I was able to run a opencl kernel without problems:
> 
> ```
> //OpenCL kernel which is run for every work item created.
> const char *saxpy_kernel =
> "__kernel                                   \n"
> "void saxpy_kernel(float alpha,     \n"
> "                  __global float *A,       \n"
> "                  __global float *B,       \n"
> "                  __global float *C)       \n"
> "{                                          \n"
> "    //Get the index of the work-item       \n"
> "    int index = get_global_id(0);          \n"
> "    C[index] = alpha* A[index] + B[index]; \n"
> "}  
> ```

Thanks a lot for testing on Linux 6.1!

> I am interested only in OpenCL capability, please let me know if you need any kind of additional tests.

Ok. I look into your patch then.

**Comment by cbalint13** [comment]
> Thanks a lot for testing on Linux 6.1!
> 
> > I am interested only in OpenCL capability, please let me know if you need any kind of additional tests.
> 
> Ok. I look into your patch then.

Thank you for investigating !
Please let me know if would like to help with other kind (non opencl) tests.

**Comment by giuliobenetti** [comment]
> > Thanks a lot for testing on Linux 6.1!
> > > I am interested only in OpenCL capability, please let me know if you need any kind of additional tests.
> > 
> > 
> > Ok. I look into your patch then.
> 
> Thank you for investigating ! Please let me know if would like to help with other kind (non opencl) tests.

That would help a lot.
I've opened #7 for Linux 6.2 and now I close this Issue, let's continue there. Thank you
